// AUTO-GENERATED by scripts/generate-product-images.mjs — do not edit by hand.
// Maps each SKU to its photos in public/products/ (<SKU>.jpg primary, <SKU>-N.jpg extras).
// Regenerated automatically on `npm run dev` and `npm run build`.

export const productImages: Record<string, string[]> = {
  "AIR-IW-34-1200": [
    "/products/AIR-IW-34-1200.jpg"
  ],
  "CAR-CW-100": [
    "/products/CAR-CW-100.jpg"
  ],
  "RAD-P-110": [
    "/products/RAD-P-110.jpg"
  ],
  "TPM-TOOL-PRO": [
    "/products/TPM-TOOL-PRO.jpg",
    "/products/TPM-TOOL-PRO-2.jpg",
    "/products/TPM-TOOL-PRO-3.jpg"
  ],
  "TW-NOR-300": [
    "/products/TW-NOR-300.jpg"
  ],
  "TW-NOR-800": [
    "/products/TW-NOR-800.jpg"
  ]
};
